				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div id="results"></div>
						<div class="row">
							<div class="col-lg-12 col-mg-12 col-sm-12 col-xs-12">
								<p id="addr"></p>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12 col-mg-12 col-sm-12 col-xs-12">
								<p id="txid"></p>
							</div>
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div id="game"></div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12 col-mg-12 col-sm-12 col-xs-12">
						<h3>Recent Games</h3>
						<div id="transactions"></div>
					</div>
				</div>

				<div class="modal fade" id="resultsPopup" tabindex="-1" role="dialog" aria-labelledby="Results" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								<h4 class="modal-title" id="results-title"></h4>
							</div>
							<div class="modal-body" id="results-body"></div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="footer">
				<p>
					&copy; <span class="name"></span> 2014
						&middot;
					<a href="#!about" data-action="about">About</a>
						&middot;
					<a href="#!contact" data-action="contact">Contact</a>
				</p>
			</div>
		</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
<script src="//crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js"></script>
<script src="/assets/js/play.js"></script>
	</body>
</html>