<html lang="pt_br">
   <div style="height:50%; width:100%;">
 <head>
    <title>Crowd Forex</title>
    <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendHttpEquiv('Content-Type',
                'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt_br');
        ?>
         <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('../vendor/twbs/bootstrap/dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('theme/Bootstrap/offcanvas.css'))
            ->prependStylesheet($this->basePath('theme/Bootstrap/signin.css'))
            
        ?>
  </head>
<body>
         <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand mr-auto mr-lg-0" href="#">Crowd Forex</a>
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Notifications</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">My Wallet</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Switch account</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


    <div style="margin-top:-170px;" class="nav-scroller bg-white shadow-sm">
      <nav class="nav nav-underline">
        <a class="nav-link active" href="#">Dashboard</a>
    
        <a class="nav-link" href="#">Forex</a>
        <a class="nav-link" href="#">A&ccedil;&otilde;es</a>
        <a class="nav-link" href="#">Traders</a>
        <a class="nav-link" href="#">Corretoras</a>
        <a class="nav-link" href="#">Opera&ccedil;&otilde;es</a>
        <a class="nav-link" href="#">Rendimentos Mensais</a>
        
       
        <a class="nav-link" href="#">
          Balance
          <span class="badge badge-pill bg-light align-text-bottom">2.00000000 BTC</span>
        </a>
      </nav>
    </div>

             <?php echo $this->content;?>
             
             <!-- footer content -->

    

   
    <!-- Scripts -->
        <?= $this->headScript()
            
            ->prependFile($this->basePath('theme/Bootstrap/offcanvas.js'))
            ->prependFile($this->basePath('../vendor/twbs/bootstrap/dist/js/vendor/popper.min.js'))
            ->prependFile($this->basePath('../vendor/twbs/bootstrap/js/src/modal.js'))
            ->prependFile($this->basePath('../vendor/twbs/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('theme/Bootstrap/assets/js/vendor/jquery.min.js'))
       ?>

  
</div>
</div>
</div>
  </body>
</html>
